id: P469A97F6
initial_creation_type: input
source_metadata:
  title: Three Deities of Long Life
  language: bo
  description: 'Texts related to the Three Deities of Long Life (tshe lha rnam gsum),
    i.e., Amitāyus (tshe dpag med), White Tārā (sgrol dkar) and Uṣṇīṣayavijayā (rnam
    rgyal ma):'
  volume:
    c345b0e86f714e9c8ca42ed38ed71dd8:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
created_at: '2022-03-01T06:20:43.913318'
last_modified_at: '2022-03-01T06:20:43.913321'
statistics:
  total_words: 1473
  total_non_words: 125
quality:
  non_words_ratio: 0.08
